### ISSUE TITLE
Issues with run.wsf

### ISSUE THREAD

**Issue by balintba** [wleepang/DesktopDeployR#19]
Hello,

first of all I would like to thank you for providing this framework, which is really nice.
Although I am really not good at similar things, I could get it work after maybe an hour, so the 
documentations and the steps are very well written.

I have a strange issue, which is the following: I can run the app, it takes some time, but it loads
all of the dependencies and opens the browser. However after I close it and try to open it again
nothing happens. After I run it as administrator the following error message pops up. Please see it below.
Once I restart the computer and run the app again, all the dependencies load, the browser opens and 
the app runs just fine. After closing it and trying to open it again the same issue with the same error message appears. Thanks for your kind help in advance!

The message is displayed on german, but it says actually that the "run.wsf" could not be found.

Best regards,
Balazs
![errormessage](https://user-images.githubusercontent.com/28111029/43343291-019a50b6-91e6-11e8-8839-9ee86e55f47e.jpg)

**Comment by wleepang** [comment]
@balintba - A couple things to check.

First, make sure that your app registers an `session$onSessionEnded` handler that stops the shiny server (if you are using shiny that is) and subsequently stops the underlying Rscript.exe process.  See the [following lines](https://github.com/wleepang/DesktopDeployR/blob/bae31b781397621db3c1c21d75c0b37b4be59aa8/app/shiny/server.R#L8-L13) in the example app on how to do this.  If you don't you'll be left with a zombie process that needs to be tracked down in the Task Manager and killed.

Second, when you are running as administrator, CMD.exe starts in a folder that is not where DesktopDeployR and your app is.  You'll need to `cd` to that location before trying to launch the app.  That said, you shouldn't have to launch as administrator.  It sounds like your issue is related to the point above.

**Comment by balintba** [comment]
Many thanks for your kind reply! It has worked. Sorry for the late response
