### ISSUE TITLE
Is it possible to have R run interactively?

### ISSUE THREAD

**Issue by Anjs04** [wleepang/DesktopDeployR#9]
Using winDialog(), I get this error:
winDialog() cannot be used non-interactively

**Comment by wleepang** [comment]
It is probably possible to change the executable to `R.exe` and use the `-f` option for the core runner script in `dist/`.

Can you clarify your use case - e.g. is this for a shiny based app?

**Comment by Anjs04** [comment]
This is to use the winDialog() function, and other base GUI functions like file.choose() and choose.dir(). Would DesktopDeployR work as is with other functions that replace these?

**Comment by Anjs04** [comment]
Hi again, would the core runner script be the R file, the Windows Script file, or the JavaScript file? They're all in /dist and called 'run'. I've attempted this solution, but exactly do I change the executable to R.exe and use the -f option?

**Comment by wleepang** [comment]
Hi @Anjs04 - Early in development of DesktopDeployR I successfully tested both GTK and Tcl/Tk based GUIs.  If you want to keep `dist/` unmodified, I'd go down this route.  Just in case you are unfamiliar - Tcl/Tk ships with R, and is good for simple UIs.  GTK will let you build more complex UIs but at the cost of external dependencies (although I think gWidgets2 handles this automatically).

Otherwise, you would need to modify `dist/script/wsf/js/run.js`:
1. line 52: "Rscript.exe" ==> "R.exe"
2. line 53: "--vanilla" ==> "--vanilla -f"

I'll also add an enhancement issue to add this as an item that can be specified in configuration.
